### ISSUE TITLE
ToInterval in ExpressionBuilders is needed for CMS FollowUpCareforChildrenPrescribedADHDMedicationADDFHIR-0.1.000

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-cql-sdk#146] opened 2024-01-31 16:53 UTC
**Describe the bug**
``
 Hl7.Cql.Compiler.ExpressionBuilder[0]
      Building expressions for FollowUpCareforChildrenPrescribedADHDMedicationADDFHIR-0.1.000
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at Hl7.Cql.Compiler.ExpressionBuilder.GetFunctionRefReturnType(FunctionRef op, IEnumerable`1 operandTypes, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 2466
   at Hl7.Cql.Compiler.ExpressionBuilder.FunctionRef(FunctionRef op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 2325
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 584
   at Hl7.Cql.Compiler.ExpressionBuilder.As(As as, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.TypeOperators.cs:line 55
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 443
   at Hl7.Cql.Compiler.ExpressionBuilder.<>c__DisplayClass115_0.<FunctionRef>b__0(Expression operand) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 2320
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Hl7.Cql.Compiler.ExpressionBuilder.FunctionRef(FunctionRef op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 2319
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 584
   at Hl7.Cql.Compiler.ExpressionBuilder.IncludedIn(IncludedIn e, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.IntervalOperators.cs:line 174
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 623
   at Hl7.Cql.Compiler.ExpressionBuilder.SingleSourceQuery(Query query, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 1102
   at Hl7.Cql.Compiler.ExpressionBuilder.Query(Query query, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 1029
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 806
   at Hl7.Cql.Compiler.ExpressionBuilder.Build() in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 360
   at Hl7.Cql.Packaging.LibraryPackager.PackageResources(DirectoryInfo elmDirectory, DirectoryInfo cqlDirectory, DirectedGraph packageGraph, TypeResolver typeResolver, OperatorBinding operatorBinding, TypeManager typeManager, Func`2 canon, ILoggerFactory logFactory) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Packaging/LibraryPackager.cs:line 157
   at Hl7.Cql.Packaging.ResourcePackager.Package(DirectoryInfo elmDir, DirectoryInfo cqlDir, Action`1 afterPackageMutator) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Packaging/ResourcePackager.cs:line 42
   at Hl7.Cql.Packager.Program.Package(DirectoryInfo elmDir, DirectoryInfo cqlDir, DirectoryInfo csDir, DirectoryInfo fhirDir) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/PackagerCLI/Program.cs:line 109
   at Hl7.Cql.Packager.Program.Main(String[] args) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/PackagerCLI/Program.cs:line 77
``

**To Reproduce**
Measures are committed to branch inspect-cms-measures. Executing the PackagerCli in that branch will trigger the error.

**Version used:**
Current develop version of the PackagerCli

**Comment by ewoutkramer** [comment] 2024-02-02 16:38
The function `GetFunctionRefReturnType` tried to determine the return type of a function, however for the `FHIRHelper` defined functions, the cql-to-elm translator does not provide the return type in the ELM node, so it has to be determined by other means.  Evan made a hack here, which basically defines the return types of all known functions in FHIRHelpers, which is easy in the case of a `ToDate` function, but `ToInterval` is harder. Evan has provided a few specific cases that he encountered, but I am guessing we're hitting a case that was not hand coded in that function. Easiest will be to find out exactly what the case is (I cannot reproduce it, so I could not debug this specific case) and then add another hack, since Evan told me fixing this for real is hard (although we've learned quite a bit since then, maybe he knows how to fix this now).

**Comment by ewoutkramer** [comment] 2024-02-23 09:53
This was reasonably easy to fix as the return type of `ToInverval` is defined to be DateTime, so I made sure that this will be returned unless some of the exception cases that Evan created are not applicable in 162c6fc2d5c6b7646b6aad47b19b40c1c6451d90.

**Comment by ewoutkramer** [comment] 2024-03-26 10:53
This is fixed by now.

**Closed as completed by ewoutkramer** 2024-03-26 10:53 UTC

**Comment by EvanMachusakNCQA** [comment] 2024-03-26 13:50
In the 1.1 version @baseTwo  is working on, he has integrated the code for supporting cross-context queries.  That change gives the `ExpressionBuilder` class access to all of the dependent `Library` instances that are `include`d.  This lets us look up `ExpressionDef` and `FunctionDef` nodes in dependent libraries.

This is important because the reference cql-to-elm implementation does not put `resultTypeSpecifier` attributes on calls to `FHIRHelpers`.  This hack is there because since we don't have a `resultTypeSpecifier`, we either need to chase the `FunctionDef` of `ToInterval` in the `FHIRHelpers` library by having access to its `Library` instance, _or_ we needed to import the FHIR modelinfo.  Since we need all the `Library` instances _anyway_ to support cross-context queries, we should be able to figure out the result types of all `FHIRHelpers` functions using that route in the future and we should be eliminating this hack in 1.1.

**Comment by baseTwo** [comment] 2024-03-26 16:41
Fixed in PR #256 on develop 2.0
